services:
  db_mysql:
    image: mysql:latest
    container_name: transac_mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: transactional
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - .data:/var/lib/mysql